[2025-03-20T06:10:34.379+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T06:10:34.405+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_breweries_list.load_to_bronze_layer manual__2025-03-20T05:59:51.964090+00:00 [queued]>
[2025-03-20T06:10:34.554+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_breweries_list.load_to_bronze_layer manual__2025-03-20T05:59:51.964090+00:00 [queued]>
[2025-03-20T06:10:34.554+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-20T06:10:34.570+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_to_bronze_layer> on 2025-03-20 05:59:51.964090+00:00
[2025-03-20T06:10:34.579+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-20T06:10:34.581+0000] {standard_task_runner.py:72} INFO - Started process 125 to run task
[2025-03-20T06:10:34.583+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_breweries_list', 'load_to_bronze_layer', 'manual__2025-03-20T05:59:51.964090+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/bronze_layer.py', '--cfg-path', '/tmp/tmpeeqbjuf3']
[2025-03-20T06:10:34.584+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask load_to_bronze_layer
[2025-03-20T06:10:34.633+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_breweries_list.load_to_bronze_layer manual__2025-03-20T05:59:51.964090+00:00 [running]> on host da2db32bddfa
[2025-03-20T06:10:34.723+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_breweries_list' AIRFLOW_CTX_TASK_ID='load_to_bronze_layer' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T05:59:51.964090+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T05:59:51.964090+00:00'
[2025-03-20T06:10:34.725+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-20T06:10:34.726+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-20T06:10:34.726+0000] {logging_mixin.py:190} INFO - Current task name:load_to_bronze_layer state:running start_date:2025-03-20 06:10:34.406083+00:00
[2025-03-20T06:10:34.726+0000] {logging_mixin.py:190} INFO - Dag name:ETL_breweries_list and current dag run status:running
[2025-03-20T06:10:34.727+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T06:10:34.792+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 71, in load_to_minio
    csv_data = df.to_csv(index=False).enconde('utf-8')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'enconde'. Did you mean: 'encode'?
[2025-03-20T06:10:34.803+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-20T06:10:34.803+0000] {logging_mixin.py:190} INFO - Task start:2025-03-20 06:10:34.406083+00:00 end:2025-03-20 06:10:34.802752+00:00 duration:0.396669
[2025-03-20T06:10:34.804+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_bronze_layer> dag:<DAG: ETL_breweries_list> dagrun:<DagRun ETL_breweries_list @ 2025-03-20 05:59:51.964090+00:00: manual__2025-03-20T05:59:51.964090+00:00, state:running, queued_at: 2025-03-20 05:59:52.000814+00:00. externally triggered: True>
[2025-03-20T06:10:34.804+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object has no attribute 'enconde'
[2025-03-20T06:10:34.804+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ETL_breweries_list, task_id=load_to_bronze_layer, run_id=manual__2025-03-20T05:59:51.964090+00:00, execution_date=20250320T055951, start_date=20250320T061034, end_date=20250320T061034
[2025-03-20T06:10:34.836+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T06:10:34.836+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 56 for task load_to_bronze_layer ('str' object has no attribute 'enconde'; 125)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 71, in load_to_minio
    csv_data = df.to_csv(index=False).enconde('utf-8')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'enconde'. Did you mean: 'encode'?
[2025-03-20T06:10:34.878+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-20T06:10:34.902+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T06:10:34.905+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
